# Generated by Django 5.1.4 on 2024-12-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='is_batch_uplaod',
            new_name='is_batch_upload',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.resume'),
        ),
    ]
