# Generated by Django 5.1.4 on 2024-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_rename_is_batch_uplaod_resume_is_batch_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='soft_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
