# Generated by Django 5.1.4 on 2024-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_applicant_soft_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='soft_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
